[project]
name = "ml-privacy"
version = "0.1.0"
description = "Privacy Engineering course mini project 2: Loss-based Membership Inference Attack on Machine Learning Models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
